### ISSUE TITLE
The 'Download' button doesn't work anymore

### ISSUE THREAD

**Issue by mariofrei** [cozie-app/cozie-apple#69]
After pressing the Download button, the message " Please wait..." appears. Then the message disappears, and nothing happens.

**Comment by FedericoTartarini** [comment]
As previously mentioned I would disable the Download button altogether since the current implementation is very poor and prone to causing several issues. The issues I have identified and need to be fixed before re-enabling it aer:
* the download button only makes sense if the data are stored locally. It is pointless that the query button queries the data from Influx. If that is the case then the researcher should simply download the data from influx.
* the columns to query are hardcoded inside the lambda function and do not reflect the survey the participant has selected.
* slightly modifying the lambda function cases the code to break. We should have a lambda function dedicated to the download button and not a single lambda function for the chart, download button, and query the data with Python.
Unless all the above are fixed, I would disable the button and remove it from the interface.

**Comment by mariofrei** [comment]
The download button has been removed from Cozie v2.
In Cozie v3 the download button as been re-implemented and is functional.
